server:
  port: 0

spring:
  application:
    name: user-service
  cloud:
    openfeign:
      micrometer:
        enabled: true
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #   bootstrap.yml 사용안할경우
#  config:
#    import: "optional:configserver:http://localhost:8888"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: $2a$10$xvEmKZTCWTSpOGK1x9p.LepRp0Lamvbqj3nk88HDlfa5yVQxdltdK

#logging:
#  level:
##    org.springframework.security: DEBUG
#    com.dogmeeting.userservice.client: DEBUG
#  pattern:
#    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

logging:
  level:
    org.springframework.security: DEBUG
    com.dogmeeting.userservice.client: DEBUG
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce. (spring boot)

#token:
#  secret: my-very-long-secret-key-1234567890123456
#  expiration-time: 86400000 # 10 days

management:
  tracing:
    sampling:
      probability: 1.0      # 1.0이면 100% 샘플링 (개발/테스트 환경에서 유용)
  propagation:
    consume: w3c
    produce: w3c
    otlp:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans   # Zipkin HTTP endpoint 사용
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh
